version: '3'
services:
  # command: ["./wait-for-it.sh", "database:3306", "--", "mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]

  database:
    image: mysql:8.2.0
    # volumes:
    # - ./config/mysql:/etc/mysql/conf.d
    #   - ~/volumes/jhipster/nouveauDossier/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: [ 'CMD', 'mysql', '-e', 'SHOW DATABASES;' ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: /AFTAS-Spring-Boot
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/aftas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"

  frontend:
    build:
      context: /AFTAS-Angular
    depends_on:
      - backend
    ports:
      - "80:80"
